### ISSUE TITLE
Swaggerdoc-UI throws error about duplicate key for CartItem

### ISSUE THREAD

**Issue by brienw** [labzero/adpq#191]

**Comment by eduardogdo** [comment]
i Have this too, i don'tknow if error reproduce for the data type or why
https://online.swagger.io/validator/debug?url=https://payphone-payments.azurewebsites.net/swagger/docs/v1
{"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"uniqueItems","message":"array must not contain duplicate elements","schema":{"loadingURI":"http://json-schema.org/draft-04/schema#","pointer":"/properties/enum"},"instance":{"pointer":"/definitions/PayPhone.PaymentButton.Business.Models.CancelResponseModel/properties/statusCode/enum"}}]}

**Comment by zohaib055** [comment]
is this resolved ?

**Comment by JeffreyATW** [comment]
This bug is specific to our project. If you're having this same issue, look for duplicate keys in your own schema.
